name: releaser

on:
  release:
    types:
      - created
jobs:
  release-to-cargo:
    runs-on: ubuntu-latest
    steps:
      - name: Chekout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - 
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: Publish to crates.io
        shell: bash
        env:
          CRATES_API_KEY: ${{ secrets.CRATES_API_KEY }}
        run: |
          cargo login "$CRATES_API_KEY"
          cargo publish --dry-run
          cargo publish
